<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <AssemblyTitle></AssemblyTitle>
    <UserSecretsId>5515585f-4177-4510-834d-fd3605e7bd79</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <None Include="configs\cluster.settings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.2-preview.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="System.CommandLine" Version="2.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RaftConsensusOnAspnet.RaftConsensus.Core\RaftConsensusOnAspnet.RaftConsensus.Core.csproj" />
  </ItemGroup>

</Project>
